[package]
name = "ejercicio4"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ejercicio4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"