[package]
name = "ejercicio2"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "ejercicio2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
